import type { CopyColorFormat } from './types'

/**
 * Choose an output format for alpha adjustment from the original source text.
 *
 * @param text - Original source text covered by the hover range.
 * @returns Presentation format used for replacement.
 */
export function getFormatForSourceText(text: string): CopyColorFormat {
  const normalized = text.trim().toLowerCase()

  if (normalized.startsWith('#') || normalized.startsWith('0x')) {
    return 'hex'
  }

  if (normalized.startsWith('hsl')) {
    return 'hsl'
  }

  if (normalized.startsWith('oklch')) {
    return 'oklch'
  }

  return 'rgb'
}

/**
 * Preserve uppercase style for HEX-like source values.
 *
 * @param value - Lowercase HEX value generated by presentations.
 * @param originalText - Original source text.
 * @returns HEX value with source text casing applied.
 */
export function preserveHexCase(value: string, originalText: string): string {
  return shouldUseUppercaseHex(originalText) ? value.toUpperCase() : value
}

/**
 * Check whether HEX output should use uppercase letters.
 *
 * @param text - Original source text.
 * @returns Whether the text uses uppercase HEX letters only.
 */
function shouldUseUppercaseHex(text: string): boolean {
  const hexLetters = text.replace(/^#|^0x/iu, '').replaceAll(/[^a-f]/giu, '')
  return /[A-F]/u.test(hexLetters) && !/[a-f]/u.test(hexLetters)
}
