import { defineExtension } from 'reactive-vscode'
import { version } from '../package.json'
import { useColorDependencyRevision } from './extension/color-dependency-revision'
import { useCommands } from './extension/commands'
import { useColorNavigation } from './features/color-navigation/use-color-navigation'
import { useColorProvider } from './features/color-provider/use-color-provider'
import { useContrastDiagnostics } from './features/contrast/use-contrast-diagnostics'
import { useColorHighlight } from './features/highlight/use-color-highlight'
import { useColorHover } from './features/hover/use-color-hover'
import { logger } from './shared/logger'

/**
 * VS Code extension lifecycle hooks generated by reactive-vscode.
 */
const { activate, deactivate } = defineExtension(() => {
  logger.info(`✅ Activated, version: ${version} `)

  const colorDependencyRevision = useColorDependencyRevision()
  useCommands()
  useColorHighlight(colorDependencyRevision)
  useColorHover(colorDependencyRevision)
  useColorNavigation()
  useColorProvider()
  useContrastDiagnostics(colorDependencyRevision)
})

export { activate, deactivate }
