import { defineExtension } from 'reactive-vscode'
import { version } from '../package.json'
import { useCommands } from './commands'
import { useColorHighlight } from './composables/use-color-highlight'
import { useColorHover } from './composables/use-color-hover'
import { logger } from './utils/logger'

/**
 * VS Code extension lifecycle hooks generated by reactive-vscode.
 */
const { activate, deactivate } = defineExtension(() => {
  logger.info(`✅ Activated, version: ${version} `)

  useCommands()
  useColorHighlight()
  useColorHover()
})

export { activate, deactivate }
