// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "ntnyq"
export const name = "vscode-better-color-highlight"
export const version = "0.5.0"
export const displayName = "Better Color Highlight"
export const description = "Highlight and preview colors in multiple formats across code, comments, and strings."
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey =
  | "color-highlight.enable"
  | "color-highlight.disable"
  | "color-highlight.copyColorAsHex"
  | "color-highlight.copyColorAsRgb"
  | "color-highlight.copyColorAsHsl"
  | "color-highlight.copyColorAsOklch"
  | "color-highlight.replaceColorAsHex"
  | "color-highlight.replaceColorAsRgb"
  | "color-highlight.replaceColorAsHsl"
  | "color-highlight.replaceColorAsOklch"
  | "color-highlight.adjustColorAlpha"
  | "color-highlight.showWorkspacePalette"
  | "color-highlight.checkColorContrast"

/**
 * Commands map registered by `ntnyq.vscode-better-color-highlight`
 */
export const commands = {
  /**
   * Enable Better Color Highlight
   * @value `color-highlight.enable`
   */
  enable: "color-highlight.enable",
  /**
   * Disable Better Color Highlight
   * @value `color-highlight.disable`
   */
  disable: "color-highlight.disable",
  /**
   * Copy Color as HEX
   * @value `color-highlight.copyColorAsHex`
   */
  copyColorAsHex: "color-highlight.copyColorAsHex",
  /**
   * Copy Color as RGB
   * @value `color-highlight.copyColorAsRgb`
   */
  copyColorAsRgb: "color-highlight.copyColorAsRgb",
  /**
   * Copy Color as HSL
   * @value `color-highlight.copyColorAsHsl`
   */
  copyColorAsHsl: "color-highlight.copyColorAsHsl",
  /**
   * Copy Color as OKLCH
   * @value `color-highlight.copyColorAsOklch`
   */
  copyColorAsOklch: "color-highlight.copyColorAsOklch",
  /**
   * Replace Color as HEX
   * @value `color-highlight.replaceColorAsHex`
   */
  replaceColorAsHex: "color-highlight.replaceColorAsHex",
  /**
   * Replace Color as RGB
   * @value `color-highlight.replaceColorAsRgb`
   */
  replaceColorAsRgb: "color-highlight.replaceColorAsRgb",
  /**
   * Replace Color as HSL
   * @value `color-highlight.replaceColorAsHsl`
   */
  replaceColorAsHsl: "color-highlight.replaceColorAsHsl",
  /**
   * Replace Color as OKLCH
   * @value `color-highlight.replaceColorAsOklch`
   */
  replaceColorAsOklch: "color-highlight.replaceColorAsOklch",
  /**
   * Adjust Color Alpha
   * @value `color-highlight.adjustColorAlpha`
   */
  adjustColorAlpha: "color-highlight.adjustColorAlpha",
  /**
   * Show Workspace Palette
   * @value `color-highlight.showWorkspacePalette`
   */
  showWorkspacePalette: "color-highlight.showWorkspacePalette",
  /**
   * Check Color Contrast
   * @value `color-highlight.checkColorContrast`
   */
  checkColorContrast: "color-highlight.checkColorContrast",
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */
export type ConfigKey =
  | "color-highlight.enable"
  | "color-highlight.languages"
  | "color-highlight.matchWords"
  | "color-highlight.namedColorMatchMode"
  | "color-highlight.enableHover"
  | "color-highlight.enableColorPicker"
  | "color-highlight.enableContrastDiagnostics"
  | "color-highlight.enableColorNavigation"
  | "color-highlight.tailwindColorMode"
  | "color-highlight.tailwindStylesheetPaths"
  | "color-highlight.resolveScssVariablesAcrossFiles"
  | "color-highlight.scssLoadPaths"
  | "color-highlight.resolveCssVariablesAcrossFiles"
  | "color-highlight.cssVariablePaths"
  | "color-highlight.cssVariableTrustedSelectors"
  | "color-highlight.maxFileSize"
  | "color-highlight.workspacePaletteInclude"
  | "color-highlight.workspacePaletteExclude"
  | "color-highlight.designTokenJsonMode"
  | "color-highlight.resolveDesignTokensAcrossFiles"
  | "color-highlight.useARGB"
  | "color-highlight.matchRgbWithNoFunction"
  | "color-highlight.rgbWithNoFunctionLanguages"
  | "color-highlight.matchHslWithNoFunction"
  | "color-highlight.hslWithNoFunctionLanguages"
  | "color-highlight.markerType"
  | "color-highlight.markRuler"
  | "color-highlight.debug"

export interface ConfigKeyTypeMap {
  "color-highlight.enable": boolean,
  "color-highlight.languages": string[],
  "color-highlight.matchWords": boolean,
  "color-highlight.namedColorMatchMode": ("context" | "always" | "never"),
  "color-highlight.enableHover": boolean,
  "color-highlight.enableColorPicker": boolean,
  "color-highlight.enableContrastDiagnostics": boolean,
  "color-highlight.enableColorNavigation": boolean,
  "color-highlight.tailwindColorMode": ("auto" | "v3" | "v4"),
  "color-highlight.tailwindStylesheetPaths": string[],
  "color-highlight.resolveScssVariablesAcrossFiles": boolean,
  "color-highlight.scssLoadPaths": string[],
  "color-highlight.resolveCssVariablesAcrossFiles": boolean,
  "color-highlight.cssVariablePaths": string[],
  "color-highlight.cssVariableTrustedSelectors": string[],
  "color-highlight.maxFileSize": number,
  "color-highlight.workspacePaletteInclude": string,
  "color-highlight.workspacePaletteExclude": string,
  "color-highlight.designTokenJsonMode": ("token-values" | "strings" | "all" | "off"),
  "color-highlight.resolveDesignTokensAcrossFiles": boolean,
  "color-highlight.useARGB": boolean,
  "color-highlight.matchRgbWithNoFunction": boolean,
  "color-highlight.rgbWithNoFunctionLanguages": string[],
  "color-highlight.matchHslWithNoFunction": boolean,
  "color-highlight.hslWithNoFunctionLanguages": string[],
  "color-highlight.markerType": ("background" | "outline" | "foreground" | "underline" | "dot-before" | "dot-after"),
  "color-highlight.markRuler": boolean,
  "color-highlight.debug": boolean,
}

export interface ConfigShorthandMap {
  enable: "color-highlight.enable",
  languages: "color-highlight.languages",
  matchWords: "color-highlight.matchWords",
  namedColorMatchMode: "color-highlight.namedColorMatchMode",
  enableHover: "color-highlight.enableHover",
  enableColorPicker: "color-highlight.enableColorPicker",
  enableContrastDiagnostics: "color-highlight.enableContrastDiagnostics",
  enableColorNavigation: "color-highlight.enableColorNavigation",
  tailwindColorMode: "color-highlight.tailwindColorMode",
  tailwindStylesheetPaths: "color-highlight.tailwindStylesheetPaths",
  resolveScssVariablesAcrossFiles: "color-highlight.resolveScssVariablesAcrossFiles",
  scssLoadPaths: "color-highlight.scssLoadPaths",
  resolveCssVariablesAcrossFiles: "color-highlight.resolveCssVariablesAcrossFiles",
  cssVariablePaths: "color-highlight.cssVariablePaths",
  cssVariableTrustedSelectors: "color-highlight.cssVariableTrustedSelectors",
  maxFileSize: "color-highlight.maxFileSize",
  workspacePaletteInclude: "color-highlight.workspacePaletteInclude",
  workspacePaletteExclude: "color-highlight.workspacePaletteExclude",
  designTokenJsonMode: "color-highlight.designTokenJsonMode",
  resolveDesignTokensAcrossFiles: "color-highlight.resolveDesignTokensAcrossFiles",
  useARGB: "color-highlight.useARGB",
  matchRgbWithNoFunction: "color-highlight.matchRgbWithNoFunction",
  rgbWithNoFunctionLanguages: "color-highlight.rgbWithNoFunctionLanguages",
  matchHslWithNoFunction: "color-highlight.matchHslWithNoFunction",
  hslWithNoFunctionLanguages: "color-highlight.hslWithNoFunctionLanguages",
  markerType: "color-highlight.markerType",
  markRuler: "color-highlight.markRuler",
  debug: "color-highlight.debug",
}

export interface ConfigShorthandTypeMap {
  enable: boolean,
  languages: string[],
  matchWords: boolean,
  namedColorMatchMode: ("context" | "always" | "never"),
  enableHover: boolean,
  enableColorPicker: boolean,
  enableContrastDiagnostics: boolean,
  enableColorNavigation: boolean,
  tailwindColorMode: ("auto" | "v3" | "v4"),
  tailwindStylesheetPaths: string[],
  resolveScssVariablesAcrossFiles: boolean,
  scssLoadPaths: string[],
  resolveCssVariablesAcrossFiles: boolean,
  cssVariablePaths: string[],
  cssVariableTrustedSelectors: string[],
  maxFileSize: number,
  workspacePaletteInclude: string,
  workspacePaletteExclude: string,
  designTokenJsonMode: ("token-values" | "strings" | "all" | "off"),
  resolveDesignTokensAcrossFiles: boolean,
  useARGB: boolean,
  matchRgbWithNoFunction: boolean,
  rgbWithNoFunctionLanguages: string[],
  matchHslWithNoFunction: boolean,
  hslWithNoFunctionLanguages: string[],
  markerType: ("background" | "outline" | "foreground" | "underline" | "dot-before" | "dot-after"),
  markRuler: boolean,
  debug: boolean,
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T,
  default: ConfigKeyTypeMap[T],
}


/**
 * Configs map registered by `ntnyq.vscode-better-color-highlight`
 */
export const configs = {
  /**
   * Enable or disable color highlighting.
   * @key `color-highlight.enable`
   * @default `true`
   * @type `boolean`
   */
  enable: {
    key: "color-highlight.enable",
    default: true,
  } as ConfigItem<"color-highlight.enable">,
  /**
   * Language IDs where colors are highlighted. Use '*' for all languages, prefix with '!' to exclude.
   * @key `color-highlight.languages`
   * @default `["*"]`
   * @type `array`
   */
  languages: {
    key: "color-highlight.languages",
    default: ["*"],
  } as ConfigItem<"color-highlight.languages">,
  /**
   * Highlight named CSS colors (e.g., 'red', 'blue') in non-style languages.
   * @key `color-highlight.matchWords`
   * @default `false`
   * @type `boolean`
   */
  matchWords: {
    key: "color-highlight.matchWords",
    default: false,
  } as ConfigItem<"color-highlight.matchWords">,
  /**
   * Controls named CSS color matching. 'context' matches style-language declaration values, 'always' matches standalone values and non-style language words, and 'never' disables named color matching.
   * @key `color-highlight.namedColorMatchMode`
   * @default `"context"`
   * @type `string`
   */
  namedColorMatchMode: {
    key: "color-highlight.namedColorMatchMode",
    default: "context",
  } as ConfigItem<"color-highlight.namedColorMatchMode">,
  /**
   * Show hover details and copy actions for highlighted colors.
   * @key `color-highlight.enableHover`
   * @default `false`
   * @type `boolean`
   */
  enableHover: {
    key: "color-highlight.enableHover",
    default: false,
  } as ConfigItem<"color-highlight.enableHover">,
  /**
   * Use VS Code's native color picker and replacement presentations for detected colors.
   * @key `color-highlight.enableColorPicker`
   * @default `false`
   * @type `boolean`
   */
  enableColorPicker: {
    key: "color-highlight.enableColorPicker",
    default: false,
  } as ConfigItem<"color-highlight.enableColorPicker">,
  /**
   * Report low contrast only for deterministic foreground/background pairs in open documents.
   * @key `color-highlight.enableContrastDiagnostics`
   * @default `false`
   * @type `boolean`
   */
  enableContrastDiagnostics: {
    key: "color-highlight.enableContrastDiagnostics",
    default: false,
  } as ConfigItem<"color-highlight.enableContrastDiagnostics">,
  /**
   * Enable Go to Definition and Peek Definition for supported color variables and design-token aliases.
   * @key `color-highlight.enableColorNavigation`
   * @default `true`
   * @type `boolean`
   */
  enableColorNavigation: {
    key: "color-highlight.enableColorNavigation",
    default: true,
  } as ConfigItem<"color-highlight.enableColorNavigation">,
  /**
   * Select the Tailwind color palette: auto detects CSS-first v4 signals, while v3 and v4 force that palette version.
   * @key `color-highlight.tailwindColorMode`
   * @default `"auto"`
   * @type `string`
   */
  tailwindColorMode: {
    key: "color-highlight.tailwindColorMode",
    default: "auto",
  } as ConfigItem<"color-highlight.tailwindColorMode">,
  /**
   * File, directory, or glob paths used as Tailwind CSS theme sources in trusted workspaces.
   * @key `color-highlight.tailwindStylesheetPaths`
   * @default `[]`
   * @type `array`
   */
  tailwindStylesheetPaths: {
    key: "color-highlight.tailwindStylesheetPaths",
    default: [],
  } as ConfigItem<"color-highlight.tailwindStylesheetPaths">,
  /**
   * Resolve SCSS variables through local @use, @forward, and @import dependencies. Disabled by default to avoid extra file-system work.
   * @key `color-highlight.resolveScssVariablesAcrossFiles`
   * @default `false`
   * @type `boolean`
   */
  resolveScssVariablesAcrossFiles: {
    key: "color-highlight.resolveScssVariablesAcrossFiles",
    default: false,
  } as ConfigItem<"color-highlight.resolveScssVariablesAcrossFiles">,
  /**
   * Additional Sass load paths for resolving non-relative SCSS @use, @forward, and @import modules.
   * @key `color-highlight.scssLoadPaths`
   * @default `[]`
   * @type `array`
   */
  scssLoadPaths: {
    key: "color-highlight.scssLoadPaths",
    default: [],
  } as ConfigItem<"color-highlight.scssLoadPaths">,
  /**
   * Resolve CSS custom properties from configured CSS variable source paths. Disabled by default to avoid extra file-system work and ambiguous cascade guesses.
   * @key `color-highlight.resolveCssVariablesAcrossFiles`
   * @default `false`
   * @type `boolean`
   */
  resolveCssVariablesAcrossFiles: {
    key: "color-highlight.resolveCssVariablesAcrossFiles",
    default: false,
  } as ConfigItem<"color-highlight.resolveCssVariablesAcrossFiles">,
  /**
   * File, directory, or glob paths used as external CSS custom property sources when CSS variable resolution is enabled.
   * @key `color-highlight.cssVariablePaths`
   * @default `[]`
   * @type `array`
   */
  cssVariablePaths: {
    key: "color-highlight.cssVariablePaths",
    default: [],
  } as ConfigItem<"color-highlight.cssVariablePaths">,
  /**
   * Selectors whose custom property declarations are trusted for cross-file CSS variable color resolution.
   * @key `color-highlight.cssVariableTrustedSelectors`
   * @default `[":root","html","body",":host"]`
   * @type `array`
   */
  cssVariableTrustedSelectors: {
    key: "color-highlight.cssVariableTrustedSelectors",
    default: [":root","html","body",":host"],
  } as ConfigItem<"color-highlight.cssVariableTrustedSelectors">,
  /**
   * Maximum document text length, in characters, to scan for color highlighting. Set to 0 to disable this size limit.
   * @key `color-highlight.maxFileSize`
   * @default `1000000`
   * @type `number`
   */
  maxFileSize: {
    key: "color-highlight.maxFileSize",
    default: 1000000,
  } as ConfigItem<"color-highlight.maxFileSize">,
  /**
   * Glob pattern that includes files in explicit workspace palette scans.
   * @key `color-highlight.workspacePaletteInclude`
   * @default `"**\/*"`
   * @type `string`
   */
  workspacePaletteInclude: {
    key: "color-highlight.workspacePaletteInclude",
    default: "**/*",
  } as ConfigItem<"color-highlight.workspacePaletteInclude">,
  /**
   * Glob pattern that excludes files from explicit workspace palette scans.
   * @key `color-highlight.workspacePaletteExclude`
   * @default `"{**\/.git/**,**\/node_modules/**,**\/dist/**,**\/build/**,**\/coverage/**}"`
   * @type `string`
   */
  workspacePaletteExclude: {
    key: "color-highlight.workspacePaletteExclude",
    default: "{**/.git/**,**/node_modules/**,**/dist/**,**/build/**,**/coverage/**}",
  } as ConfigItem<"color-highlight.workspacePaletteExclude">,
  /**
   * Controls design token color matching. For JSON, JSONC, and .tokens files, 'token-values' matches value and $value fields, 'strings' matches any color string value, and 'all' enables both modes. 'off' disables JSON, JSONC, .tokens, and YAML token matching.
   * @key `color-highlight.designTokenJsonMode`
   * @default `"token-values"`
   * @type `string`
   */
  designTokenJsonMode: {
    key: "color-highlight.designTokenJsonMode",
    default: "token-values",
  } as ConfigItem<"color-highlight.designTokenJsonMode">,
  /**
   * Resolve relative JSON, JSONC, JSON-formatted .tokens, and YAML design-token $ref references across files in trusted workspaces.
   * @key `color-highlight.resolveDesignTokensAcrossFiles`
   * @default `false`
   * @type `boolean`
   */
  resolveDesignTokensAcrossFiles: {
    key: "color-highlight.resolveDesignTokensAcrossFiles",
    default: false,
  } as ConfigItem<"color-highlight.resolveDesignTokensAcrossFiles">,
  /**
   * Interpret 8-digit hex colors as ARGB instead of RGBA.
   * @key `color-highlight.useARGB`
   * @default `false`
   * @type `boolean`
   */
  useARGB: {
    key: "color-highlight.useARGB",
    default: false,
  } as ConfigItem<"color-highlight.useARGB">,
  /**
   * Highlight RGB values not wrapped in rgb() function.
   * @key `color-highlight.matchRgbWithNoFunction`
   * @default `false`
   * @type `boolean`
   */
  matchRgbWithNoFunction: {
    key: "color-highlight.matchRgbWithNoFunction",
    default: false,
  } as ConfigItem<"color-highlight.matchRgbWithNoFunction">,
  /**
   * Language IDs for rgb-without-function matching. Use '*' / '!' syntax.
   * @key `color-highlight.rgbWithNoFunctionLanguages`
   * @default `["*"]`
   * @type `array`
   */
  rgbWithNoFunctionLanguages: {
    key: "color-highlight.rgbWithNoFunctionLanguages",
    default: ["*"],
  } as ConfigItem<"color-highlight.rgbWithNoFunctionLanguages">,
  /**
   * Highlight HSL values not wrapped in hsl() function.
   * @key `color-highlight.matchHslWithNoFunction`
   * @default `false`
   * @type `boolean`
   */
  matchHslWithNoFunction: {
    key: "color-highlight.matchHslWithNoFunction",
    default: false,
  } as ConfigItem<"color-highlight.matchHslWithNoFunction">,
  /**
   * Language IDs for hsl-without-function matching. Use '*' / '!' syntax.
   * @key `color-highlight.hslWithNoFunctionLanguages`
   * @default `["*"]`
   * @type `array`
   */
  hslWithNoFunctionLanguages: {
    key: "color-highlight.hslWithNoFunctionLanguages",
    default: ["*"],
  } as ConfigItem<"color-highlight.hslWithNoFunctionLanguages">,
  /**
   * Style of the color highlight marker.
   * @key `color-highlight.markerType`
   * @default `"background"`
   * @type `string`
   */
  markerType: {
    key: "color-highlight.markerType",
    default: "background",
  } as ConfigItem<"color-highlight.markerType">,
  /**
   * Show color indicators on the scrollbar ruler.
   * @key `color-highlight.markRuler`
   * @default `true`
   * @type `boolean`
   */
  markRuler: {
    key: "color-highlight.markRuler",
    default: true,
  } as ConfigItem<"color-highlight.markRuler">,
  /**
   * Enable debug logging for color detection and decoration.
   * @key `color-highlight.debug`
   * @default `false`
   * @type `boolean`
   */
  debug: {
    key: "color-highlight.debug",
    default: false,
  } as ConfigItem<"color-highlight.debug">,
}

export interface ScopedConfigKeyTypeMap {
  "enable": boolean,
  "languages": string[],
  "matchWords": boolean,
  "namedColorMatchMode": ("context" | "always" | "never"),
  "enableHover": boolean,
  "enableColorPicker": boolean,
  "enableContrastDiagnostics": boolean,
  "enableColorNavigation": boolean,
  "tailwindColorMode": ("auto" | "v3" | "v4"),
  "tailwindStylesheetPaths": string[],
  "resolveScssVariablesAcrossFiles": boolean,
  "scssLoadPaths": string[],
  "resolveCssVariablesAcrossFiles": boolean,
  "cssVariablePaths": string[],
  "cssVariableTrustedSelectors": string[],
  "maxFileSize": number,
  "workspacePaletteInclude": string,
  "workspacePaletteExclude": string,
  "designTokenJsonMode": ("token-values" | "strings" | "all" | "off"),
  "resolveDesignTokensAcrossFiles": boolean,
  "useARGB": boolean,
  "matchRgbWithNoFunction": boolean,
  "rgbWithNoFunctionLanguages": string[],
  "matchHslWithNoFunction": boolean,
  "hslWithNoFunctionLanguages": string[],
  "markerType": ("background" | "outline" | "foreground" | "underline" | "dot-before" | "dot-after"),
  "markRuler": boolean,
  "debug": boolean,
}

export const scopedConfigs = {
  scope: "color-highlight",
  defaults: {
    "enable": true,
    "languages": ["*"],
    "matchWords": false,
    "namedColorMatchMode": "context",
    "enableHover": false,
    "enableColorPicker": false,
    "enableContrastDiagnostics": false,
    "enableColorNavigation": true,
    "tailwindColorMode": "auto",
    "tailwindStylesheetPaths": [],
    "resolveScssVariablesAcrossFiles": false,
    "scssLoadPaths": [],
    "resolveCssVariablesAcrossFiles": false,
    "cssVariablePaths": [],
    "cssVariableTrustedSelectors": [":root","html","body",":host"],
    "maxFileSize": 1000000,
    "workspacePaletteInclude": "**/*",
    "workspacePaletteExclude": "{**/.git/**,**/node_modules/**,**/dist/**,**/build/**,**/coverage/**}",
    "designTokenJsonMode": "token-values",
    "resolveDesignTokensAcrossFiles": false,
    "useARGB": false,
    "matchRgbWithNoFunction": false,
    "rgbWithNoFunctionLanguages": ["*"],
    "matchHslWithNoFunction": false,
    "hslWithNoFunctionLanguages": ["*"],
    "markerType": "background",
    "markRuler": true,
    "debug": false,
  } satisfies ScopedConfigKeyTypeMap,
}

export interface NestedConfigs {
  "color-highlight": {
    "enable": boolean,
    "languages": string[],
    "matchWords": boolean,
    "namedColorMatchMode": ("context" | "always" | "never"),
    "enableHover": boolean,
    "enableColorPicker": boolean,
    "enableContrastDiagnostics": boolean,
    "enableColorNavigation": boolean,
    "tailwindColorMode": ("auto" | "v3" | "v4"),
    "tailwindStylesheetPaths": string[],
    "resolveScssVariablesAcrossFiles": boolean,
    "scssLoadPaths": string[],
    "resolveCssVariablesAcrossFiles": boolean,
    "cssVariablePaths": string[],
    "cssVariableTrustedSelectors": string[],
    "maxFileSize": number,
    "workspacePaletteInclude": string,
    "workspacePaletteExclude": string,
    "designTokenJsonMode": ("token-values" | "strings" | "all" | "off"),
    "resolveDesignTokensAcrossFiles": boolean,
    "useARGB": boolean,
    "matchRgbWithNoFunction": boolean,
    "rgbWithNoFunctionLanguages": string[],
    "matchHslWithNoFunction": boolean,
    "hslWithNoFunctionLanguages": string[],
    "markerType": ("background" | "outline" | "foreground" | "underline" | "dot-before" | "dot-after"),
    "markRuler": boolean,
    "debug": boolean,
  },
}

export interface NestedScopedConfigs {
  "enable": boolean,
  "languages": string[],
  "matchWords": boolean,
  "namedColorMatchMode": ("context" | "always" | "never"),
  "enableHover": boolean,
  "enableColorPicker": boolean,
  "enableContrastDiagnostics": boolean,
  "enableColorNavigation": boolean,
  "tailwindColorMode": ("auto" | "v3" | "v4"),
  "tailwindStylesheetPaths": string[],
  "resolveScssVariablesAcrossFiles": boolean,
  "scssLoadPaths": string[],
  "resolveCssVariablesAcrossFiles": boolean,
  "cssVariablePaths": string[],
  "cssVariableTrustedSelectors": string[],
  "maxFileSize": number,
  "workspacePaletteInclude": string,
  "workspacePaletteExclude": string,
  "designTokenJsonMode": ("token-values" | "strings" | "all" | "off"),
  "resolveDesignTokensAcrossFiles": boolean,
  "useARGB": boolean,
  "matchRgbWithNoFunction": boolean,
  "rgbWithNoFunctionLanguages": string[],
  "matchHslWithNoFunction": boolean,
  "hslWithNoFunctionLanguages": string[],
  "markerType": ("background" | "outline" | "foreground" | "underline" | "dot-before" | "dot-after"),
  "markRuler": boolean,
  "debug": boolean,
}

