// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "ntnyq"
export const name = "vscode-better-color-highlight"
export const version = "0.0.0"
export const displayName = "Better Color Highlight"
export const description = "Highlight and preview colors in multiple formats across code, comments, and strings."
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey =
  | "color-highlight.enable"
  | "color-highlight.disable"

/**
 * Commands map registered by `ntnyq.vscode-better-color-highlight`
 */
export const commands = {
  /**
   * Enable Better Color Highlight
   * @value `color-highlight.enable`
   */
  colorHighlightEnable: "color-highlight.enable",
  /**
   * Disable Better Color Highlight
   * @value `color-highlight.disable`
   */
  colorHighlightDisable: "color-highlight.disable",
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */
export type ConfigKey =
  | "color-highlight.enable"
  | "color-highlight.languages"
  | "color-highlight.matchWords"
  | "color-highlight.useARGB"
  | "color-highlight.matchRgbWithNoFunction"
  | "color-highlight.rgbWithNoFunctionLanguages"
  | "color-highlight.matchHslWithNoFunction"
  | "color-highlight.hslWithNoFunctionLanguages"
  | "color-highlight.markerType"
  | "color-highlight.markRuler"
  | "color-highlight.debug"

export interface ConfigKeyTypeMap {
  "color-highlight.enable": boolean,
  "color-highlight.languages": string[],
  "color-highlight.matchWords": boolean,
  "color-highlight.useARGB": boolean,
  "color-highlight.matchRgbWithNoFunction": boolean,
  "color-highlight.rgbWithNoFunctionLanguages": string[],
  "color-highlight.matchHslWithNoFunction": boolean,
  "color-highlight.hslWithNoFunctionLanguages": string[],
  "color-highlight.markerType": ("background" | "outline" | "foreground" | "underline" | "dot-before" | "dot-after"),
  "color-highlight.markRuler": boolean,
  "color-highlight.debug": boolean,
}

export interface ConfigShorthandMap {
  colorHighlightEnable: "color-highlight.enable",
  colorHighlightLanguages: "color-highlight.languages",
  colorHighlightMatchWords: "color-highlight.matchWords",
  colorHighlightUseARGB: "color-highlight.useARGB",
  colorHighlightMatchRgbWithNoFunction: "color-highlight.matchRgbWithNoFunction",
  colorHighlightRgbWithNoFunctionLanguages: "color-highlight.rgbWithNoFunctionLanguages",
  colorHighlightMatchHslWithNoFunction: "color-highlight.matchHslWithNoFunction",
  colorHighlightHslWithNoFunctionLanguages: "color-highlight.hslWithNoFunctionLanguages",
  colorHighlightMarkerType: "color-highlight.markerType",
  colorHighlightMarkRuler: "color-highlight.markRuler",
  colorHighlightDebug: "color-highlight.debug",
}

export interface ConfigShorthandTypeMap {
  colorHighlightEnable: boolean,
  colorHighlightLanguages: string[],
  colorHighlightMatchWords: boolean,
  colorHighlightUseARGB: boolean,
  colorHighlightMatchRgbWithNoFunction: boolean,
  colorHighlightRgbWithNoFunctionLanguages: string[],
  colorHighlightMatchHslWithNoFunction: boolean,
  colorHighlightHslWithNoFunctionLanguages: string[],
  colorHighlightMarkerType: ("background" | "outline" | "foreground" | "underline" | "dot-before" | "dot-after"),
  colorHighlightMarkRuler: boolean,
  colorHighlightDebug: boolean,
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T,
  default: ConfigKeyTypeMap[T],
}


/**
 * Configs map registered by `ntnyq.vscode-better-color-highlight`
 */
export const configs = {
  /**
   * Enable or disable color highlighting.
   * @key `color-highlight.enable`
   * @default `true`
   * @type `boolean`
   */
  colorHighlightEnable: {
    key: "color-highlight.enable",
    default: true,
  } as ConfigItem<"color-highlight.enable">,
  /**
   * Language IDs where colors are highlighted. Use '*' for all languages, prefix with '!' to exclude.
   * @key `color-highlight.languages`
   * @default `["*"]`
   * @type `array`
   */
  colorHighlightLanguages: {
    key: "color-highlight.languages",
    default: ["*"],
  } as ConfigItem<"color-highlight.languages">,
  /**
   * Highlight named CSS colors (e.g., 'red', 'blue') in all file types.
   * @key `color-highlight.matchWords`
   * @default `false`
   * @type `boolean`
   */
  colorHighlightMatchWords: {
    key: "color-highlight.matchWords",
    default: false,
  } as ConfigItem<"color-highlight.matchWords">,
  /**
   * Interpret 8-digit hex colors as ARGB instead of RGBA.
   * @key `color-highlight.useARGB`
   * @default `false`
   * @type `boolean`
   */
  colorHighlightUseARGB: {
    key: "color-highlight.useARGB",
    default: false,
  } as ConfigItem<"color-highlight.useARGB">,
  /**
   * Highlight RGB values not wrapped in rgb() function.
   * @key `color-highlight.matchRgbWithNoFunction`
   * @default `false`
   * @type `boolean`
   */
  colorHighlightMatchRgbWithNoFunction: {
    key: "color-highlight.matchRgbWithNoFunction",
    default: false,
  } as ConfigItem<"color-highlight.matchRgbWithNoFunction">,
  /**
   * Language IDs for rgb-without-function matching. Use '*' / '!' syntax.
   * @key `color-highlight.rgbWithNoFunctionLanguages`
   * @default `["*"]`
   * @type `array`
   */
  colorHighlightRgbWithNoFunctionLanguages: {
    key: "color-highlight.rgbWithNoFunctionLanguages",
    default: ["*"],
  } as ConfigItem<"color-highlight.rgbWithNoFunctionLanguages">,
  /**
   * Highlight HSL values not wrapped in hsl() function.
   * @key `color-highlight.matchHslWithNoFunction`
   * @default `false`
   * @type `boolean`
   */
  colorHighlightMatchHslWithNoFunction: {
    key: "color-highlight.matchHslWithNoFunction",
    default: false,
  } as ConfigItem<"color-highlight.matchHslWithNoFunction">,
  /**
   * Language IDs for hsl-without-function matching. Use '*' / '!' syntax.
   * @key `color-highlight.hslWithNoFunctionLanguages`
   * @default `["*"]`
   * @type `array`
   */
  colorHighlightHslWithNoFunctionLanguages: {
    key: "color-highlight.hslWithNoFunctionLanguages",
    default: ["*"],
  } as ConfigItem<"color-highlight.hslWithNoFunctionLanguages">,
  /**
   * Style of the color highlight marker.
   * @key `color-highlight.markerType`
   * @default `"background"`
   * @type `string`
   */
  colorHighlightMarkerType: {
    key: "color-highlight.markerType",
    default: "background",
  } as ConfigItem<"color-highlight.markerType">,
  /**
   * Show color indicators on the scrollbar ruler.
   * @key `color-highlight.markRuler`
   * @default `true`
   * @type `boolean`
   */
  colorHighlightMarkRuler: {
    key: "color-highlight.markRuler",
    default: true,
  } as ConfigItem<"color-highlight.markRuler">,
  /**
   * Enable debug logging for color detection and decoration.
   * @key `color-highlight.debug`
   * @default `false`
   * @type `boolean`
   */
  colorHighlightDebug: {
    key: "color-highlight.debug",
    default: false,
  } as ConfigItem<"color-highlight.debug">,
}

export interface ScopedConfigKeyTypeMap {
}

export const scopedConfigs = {
  scope: "vscode-better-color-highlight",
  defaults: {
  } satisfies ScopedConfigKeyTypeMap,
}

export interface NestedConfigs {
  "color-highlight": {
    "enable": boolean,
    "languages": string[],
    "matchWords": boolean,
    "useARGB": boolean,
    "matchRgbWithNoFunction": boolean,
    "rgbWithNoFunctionLanguages": string[],
    "matchHslWithNoFunction": boolean,
    "hslWithNoFunctionLanguages": string[],
    "markerType": ("background" | "outline" | "foreground" | "underline" | "dot-before" | "dot-after"),
    "markRuler": boolean,
    "debug": boolean,
  },
}

export interface NestedScopedConfigs {
}

