// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "ntnyq"
export const name = "vscode-better-color-highlight"
export const version = "0.0.0"
export const displayName = "Better Color Highlight"
export const description = "Highlight and preview colors in multiple formats across code, comments, and strings."
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey =
  | "color-highlight.enable"
  | "color-highlight.disable"

/**
 * Commands map registered by `ntnyq.vscode-better-color-highlight`
 */
export const commands = {
  /**
   * Enable Better Color Highlight
   * @value `color-highlight.enable`
   */
  enable: "color-highlight.enable",
  /**
   * Disable Better Color Highlight
   * @value `color-highlight.disable`
   */
  disable: "color-highlight.disable",
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */
export type ConfigKey =
  | "color-highlight.enable"
  | "color-highlight.languages"
  | "color-highlight.matchWords"
  | "color-highlight.namedColorMatchMode"
  | "color-highlight.useARGB"
  | "color-highlight.matchRgbWithNoFunction"
  | "color-highlight.rgbWithNoFunctionLanguages"
  | "color-highlight.matchHslWithNoFunction"
  | "color-highlight.hslWithNoFunctionLanguages"
  | "color-highlight.markerType"
  | "color-highlight.markRuler"
  | "color-highlight.debug"

export interface ConfigKeyTypeMap {
  "color-highlight.enable": boolean,
  "color-highlight.languages": string[],
  "color-highlight.matchWords": boolean,
  "color-highlight.namedColorMatchMode": ("context" | "always" | "never"),
  "color-highlight.useARGB": boolean,
  "color-highlight.matchRgbWithNoFunction": boolean,
  "color-highlight.rgbWithNoFunctionLanguages": string[],
  "color-highlight.matchHslWithNoFunction": boolean,
  "color-highlight.hslWithNoFunctionLanguages": string[],
  "color-highlight.markerType": ("background" | "outline" | "foreground" | "underline" | "dot-before" | "dot-after"),
  "color-highlight.markRuler": boolean,
  "color-highlight.debug": boolean,
}

export interface ConfigShorthandMap {
  enable: "color-highlight.enable",
  languages: "color-highlight.languages",
  matchWords: "color-highlight.matchWords",
  namedColorMatchMode: "color-highlight.namedColorMatchMode",
  useARGB: "color-highlight.useARGB",
  matchRgbWithNoFunction: "color-highlight.matchRgbWithNoFunction",
  rgbWithNoFunctionLanguages: "color-highlight.rgbWithNoFunctionLanguages",
  matchHslWithNoFunction: "color-highlight.matchHslWithNoFunction",
  hslWithNoFunctionLanguages: "color-highlight.hslWithNoFunctionLanguages",
  markerType: "color-highlight.markerType",
  markRuler: "color-highlight.markRuler",
  debug: "color-highlight.debug",
}

export interface ConfigShorthandTypeMap {
  enable: boolean,
  languages: string[],
  matchWords: boolean,
  namedColorMatchMode: ("context" | "always" | "never"),
  useARGB: boolean,
  matchRgbWithNoFunction: boolean,
  rgbWithNoFunctionLanguages: string[],
  matchHslWithNoFunction: boolean,
  hslWithNoFunctionLanguages: string[],
  markerType: ("background" | "outline" | "foreground" | "underline" | "dot-before" | "dot-after"),
  markRuler: boolean,
  debug: boolean,
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T,
  default: ConfigKeyTypeMap[T],
}


/**
 * Configs map registered by `ntnyq.vscode-better-color-highlight`
 */
export const configs = {
  /**
   * Enable or disable color highlighting.
   * @key `color-highlight.enable`
   * @default `true`
   * @type `boolean`
   */
  enable: {
    key: "color-highlight.enable",
    default: true,
  } as ConfigItem<"color-highlight.enable">,
  /**
   * Language IDs where colors are highlighted. Use '*' for all languages, prefix with '!' to exclude.
   * @key `color-highlight.languages`
   * @default `["*"]`
   * @type `array`
   */
  languages: {
    key: "color-highlight.languages",
    default: ["*"],
  } as ConfigItem<"color-highlight.languages">,
  /**
   * Highlight named CSS colors (e.g., 'red', 'blue') in non-style languages.
   * @key `color-highlight.matchWords`
   * @default `false`
   * @type `boolean`
   */
  matchWords: {
    key: "color-highlight.matchWords",
    default: false,
  } as ConfigItem<"color-highlight.matchWords">,
  /**
   * Controls named CSS color matching. 'context' matches style-language declaration values, 'always' matches any named color word, and 'never' disables named color matching.
   * @key `color-highlight.namedColorMatchMode`
   * @default `"context"`
   * @type `string`
   */
  namedColorMatchMode: {
    key: "color-highlight.namedColorMatchMode",
    default: "context",
  } as ConfigItem<"color-highlight.namedColorMatchMode">,
  /**
   * Interpret 8-digit hex colors as ARGB instead of RGBA.
   * @key `color-highlight.useARGB`
   * @default `false`
   * @type `boolean`
   */
  useARGB: {
    key: "color-highlight.useARGB",
    default: false,
  } as ConfigItem<"color-highlight.useARGB">,
  /**
   * Highlight RGB values not wrapped in rgb() function.
   * @key `color-highlight.matchRgbWithNoFunction`
   * @default `false`
   * @type `boolean`
   */
  matchRgbWithNoFunction: {
    key: "color-highlight.matchRgbWithNoFunction",
    default: false,
  } as ConfigItem<"color-highlight.matchRgbWithNoFunction">,
  /**
   * Language IDs for rgb-without-function matching. Use '*' / '!' syntax.
   * @key `color-highlight.rgbWithNoFunctionLanguages`
   * @default `["*"]`
   * @type `array`
   */
  rgbWithNoFunctionLanguages: {
    key: "color-highlight.rgbWithNoFunctionLanguages",
    default: ["*"],
  } as ConfigItem<"color-highlight.rgbWithNoFunctionLanguages">,
  /**
   * Highlight HSL values not wrapped in hsl() function.
   * @key `color-highlight.matchHslWithNoFunction`
   * @default `false`
   * @type `boolean`
   */
  matchHslWithNoFunction: {
    key: "color-highlight.matchHslWithNoFunction",
    default: false,
  } as ConfigItem<"color-highlight.matchHslWithNoFunction">,
  /**
   * Language IDs for hsl-without-function matching. Use '*' / '!' syntax.
   * @key `color-highlight.hslWithNoFunctionLanguages`
   * @default `["*"]`
   * @type `array`
   */
  hslWithNoFunctionLanguages: {
    key: "color-highlight.hslWithNoFunctionLanguages",
    default: ["*"],
  } as ConfigItem<"color-highlight.hslWithNoFunctionLanguages">,
  /**
   * Style of the color highlight marker.
   * @key `color-highlight.markerType`
   * @default `"background"`
   * @type `string`
   */
  markerType: {
    key: "color-highlight.markerType",
    default: "background",
  } as ConfigItem<"color-highlight.markerType">,
  /**
   * Show color indicators on the scrollbar ruler.
   * @key `color-highlight.markRuler`
   * @default `true`
   * @type `boolean`
   */
  markRuler: {
    key: "color-highlight.markRuler",
    default: true,
  } as ConfigItem<"color-highlight.markRuler">,
  /**
   * Enable debug logging for color detection and decoration.
   * @key `color-highlight.debug`
   * @default `false`
   * @type `boolean`
   */
  debug: {
    key: "color-highlight.debug",
    default: false,
  } as ConfigItem<"color-highlight.debug">,
}

export interface ScopedConfigKeyTypeMap {
  "enable": boolean,
  "languages": string[],
  "matchWords": boolean,
  "namedColorMatchMode": ("context" | "always" | "never"),
  "useARGB": boolean,
  "matchRgbWithNoFunction": boolean,
  "rgbWithNoFunctionLanguages": string[],
  "matchHslWithNoFunction": boolean,
  "hslWithNoFunctionLanguages": string[],
  "markerType": ("background" | "outline" | "foreground" | "underline" | "dot-before" | "dot-after"),
  "markRuler": boolean,
  "debug": boolean,
}

export const scopedConfigs = {
  scope: "color-highlight",
  defaults: {
    "enable": true,
    "languages": ["*"],
    "matchWords": false,
    "namedColorMatchMode": "context",
    "useARGB": false,
    "matchRgbWithNoFunction": false,
    "rgbWithNoFunctionLanguages": ["*"],
    "matchHslWithNoFunction": false,
    "hslWithNoFunctionLanguages": ["*"],
    "markerType": "background",
    "markRuler": true,
    "debug": false,
  } satisfies ScopedConfigKeyTypeMap,
}

export interface NestedConfigs {
  "color-highlight": {
    "enable": boolean,
    "languages": string[],
    "matchWords": boolean,
    "namedColorMatchMode": ("context" | "always" | "never"),
    "useARGB": boolean,
    "matchRgbWithNoFunction": boolean,
    "rgbWithNoFunctionLanguages": string[],
    "matchHslWithNoFunction": boolean,
    "hslWithNoFunctionLanguages": string[],
    "markerType": ("background" | "outline" | "foreground" | "underline" | "dot-before" | "dot-after"),
    "markRuler": boolean,
    "debug": boolean,
  },
}

export interface NestedScopedConfigs {
  "enable": boolean,
  "languages": string[],
  "matchWords": boolean,
  "namedColorMatchMode": ("context" | "always" | "never"),
  "useARGB": boolean,
  "matchRgbWithNoFunction": boolean,
  "rgbWithNoFunctionLanguages": string[],
  "matchHslWithNoFunction": boolean,
  "hslWithNoFunctionLanguages": string[],
  "markerType": ("background" | "outline" | "foreground" | "underline" | "dot-before" | "dot-after"),
  "markRuler": boolean,
  "debug": boolean,
}

