import type { CopyColorFormat } from './types'

/**
 * Choose an output format for alpha adjustment from the original source text.
 *
 * @param text - Original source text covered by the hover range.
 * @returns Presentation format used for replacement.
 */
export function getFormatForSourceText(text: string): CopyColorFormat {
  const normalized = text.trim().toLowerCase()

  if (normalized.startsWith('#') || normalized.startsWith('0x')) {
    return 'hex'
  }

  if (normalized.startsWith('hsl')) {
    return 'hsl'
  }

  if (normalized.startsWith('oklch')) {
    return 'oklch'
  }

  return 'rgb'
}

/**
 * Preserve letter case and numeric prefixes for HEX source values.
 *
 * @param value - Lowercase HEX value generated by presentations.
 * @param originalText - Original source text.
 * @returns HEX value with the original letter case and prefix.
 */
export function preserveHexStyle(value: string, originalText: string): string {
  const normalized = shouldUseUppercaseHex(originalText)
    ? value.toUpperCase()
    : value
  const numericPrefix = originalText.match(/^0x/iu)?.[0]
  return numericPrefix ? normalized.replace(/^#/u, numericPrefix) : normalized
}

/**
 * Check whether HEX output should use uppercase letters.
 *
 * @param text - Original source text.
 * @returns Whether the text uses uppercase HEX letters only.
 */
function shouldUseUppercaseHex(text: string): boolean {
  const hexLetters = text.replace(/^#|^0x/iu, '').replaceAll(/[^a-f]/giu, '')
  return /[A-F]/u.test(hexLetters) && !/[a-f]/u.test(hexLetters)
}
